### PR TITLE
Replace opencollective postinstall message

### LINKED ISSUE #1590: Postinstall advertisement
## Steps to reproduce
```sh
> npm install styled-components
```

## Expected Behavior
Package installation complete with this input:

```sh
+ styled-components@3.2.1
updated 1 package in 10.637s
```

## Actual Behavior
```sh
> styled-components@3.2.1 postinstall /node_modules/styled-components
> opencollective postinstall


                    Thanks for installing styled-components 🙏
                 Please consider donating to our open collective
                        to help us maintain this package.

                           Number of contributors: 183
                              Number of backers: 15
                              Annual budget: US$ 887
                             Current balance: US$ 545

     👉  Donate: https://opencollective.com/styled-components/donate

+ styled-components@3.2.1
updated 1 package in 11.623s
```

I'm curious, if these "stats" are required to be displayed on a `postinstall` step?

There are many Opencollective members, who do **NOT** use such awkward methods to advertise, the names include:
- Webpack
- Babel
- Vue

All of the above do **NOT** advertise through the npm's `postinstall` script.

### LINKED ISSUE #1628: opencollective dependency requires strange versions
Now that `opencollective` is a dependency (not a devDependency), it is requiring `babel-polyfill@6.23.0` whereas if it were to require `babel-polyfill@^6.23.0`, that would appropriately evaluate to `babel-polyfill@6.26.0`. There are 5 other libraries with similar exact dependencies.

In order to not install all these unnecessary duplicates, I'm now required to put overrides in the `resolutions` of my `package.json` because of `styled-components`' `postinstall` hook.

### LINKED ISSUE #1644: Dependency conflicts with React
## System:
 - OS: Windows 10
 - CPU: x64 Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
 - Free Memory: 2.06 GB
 - Total Memory: 7.89 GB
 - Shell: ¯\_(ツ)_/¯
## Binaries:
 - Node: 8.9.3
 - Yarn: 1.5.1
 - npm: 5.8.0
 - Watchman: Not Found
### styled-components:
 - wanted: ^3.2.3
 - installed: 3.2.3

## Steps to reproduce

1. Take an empty project with the following in package.json (please note `flat: true`):

```JSON
{
  "license": "UNLICENSED",
  "flat": true,
  "dependencies": {
    "react": "^16.2.0",
    "react-dom": "^16.2.0"
  }
}
```

2. Install React
```
yarn
```

3. Install SC

```
$ yarn add styled-components
```

## Expected Behavior

SC to install without issues.

## Actual Behavior

```
info Unable to find a suitable version for "core-js", please choose one by typing one of the numbers below:
  1) "core-js@^1.0.0" which resolved to "1.2.7"
  2) "core-js@^2.4.0, core-js@^2.4.0" which resolved to "2.5.4"
Answer?: 1
info Unable to find a suitable version for "node-fetch", please choose one by typing one of the numbers below:
  1) "node-fetch@^1.0.1" which resolved to "1.7.3"
  2) "node-fetch@1.6.3" which resolved to "1.6.3"
Answer?: 1
info Unable to find a suitable version for "supports-color", please choose one by typing one of the numbers below:
  1) "supports-color@^3.2.3" which resolved to "3.2.3"
  2) "supports-color@^2.0.0" which resolved to "2.0.0"
Answer?: 1
info Unable to find a suitable version for "strip-ansi", please choose one by typing one of the numbers below:
  1) "strip-ansi@^3.0.0, strip-ansi@^3.0.0" which resolved to "3.0.1"
  2) "strip-ansi@^4.0.0" which resolved to "4.0.0"
Answer?: 1
info Unable to find a suitable version for "ansi-regex", please choose one by typing one of the numbers below:
  1) "ansi-regex@^3.0.0" which resolved to "3.0.0"
  2) "ansi-regex@^2.0.0, ansi-regex@^2.0.0" which resolved to "2.1.1"
Answer?: 1
info Unable to find a suitable version for "regenerator-runtime", please choose one by typing one of the numbers below:
  1) "regenerator-runtime@^0.11.0" which resolved to "0.11.1"
  2) "regenerator-runtime@^0.10.0" which resolved to "0.10.5"
Answer?: 1
```

### LINKED ISSUE #1645: Install script contains adware
calling `npm install` has a postinstall adware script which outputs the following text:

```
Thanks for installing styled-components 🙏
                 Please consider donating to our open collective
                        to help us maintain this package.

                           Number of contributors: 186
                              Number of backers: 22
                             Annual budget: US$ 1,269
                             Current balance: US$ 687

     👉  Donate: https://opencollective.com/styled-components/donate
```

the adware script which injects the ad above should probably be removed.

It's understandable that you guys need money, but even if yours was the most important package in the folder this still would be unacceptable.

Can you imagine what it would be like if everyone did what you are doing here?  An entire console filled with advertisements?  

Please, recognize the golden rule, act as you wish others to act, and remove this adware.

### PR DESCRIPTION
**Pull request by kitten**
Some minor refactors of our scripts while I was at it:

- Swap `prepublish` with `prepublishOnly` (let's please not build on every install)
- Use `npm-run-all` where appropriate for some simplification

And what this is actually about:

- Remove `opencollective` cli package
- Add small `postinstall.js` script into `scripts/` folder

The message fulfils a couple of our new criteria:

- It's short
- It has no annoying colours or emoji since some ppl dislike that
- It's not pushy, but personal
- It just asks ppl to take a look (~donate~, ~support~)

The message reads as such:

> Take a look at https://opencollective.com/styled-components/donate to help out styled-components’ maintainers

Removing the opencollective dependency is quite important as it turns out (See #1644, #1628) as it introduces some conflicts with other packages (for no reason really) especially when using flat installs.

Fix #1644 
Fix #1628 
Fix #1645 
Fix #1590

### CODE REVIEW

File: scripts/postinstall.js [hunk 1]
```diff
@@ -0,0 +1,7 @@
+#!/usr/bin/env node
+/* eslint-disable */
+/* Adapted from nodemon's postinstall: https://github.com/remy/nodemon/blob/master/package.json */
+
+var msg = 'Take a look at https://opencollective.com/styled-components/donate to help out styled-components’ maintainers';
```
Comment (mxstbr) [inline scripts/postinstall.js]: Let's not link directly to /donate?

Comment (kitten) [reply scripts/postinstall.js]: good call :+1:

File: scripts/postinstall.js [hunk 2]
```diff
@@ -0,0 +1,7 @@
+#!/usr/bin/env node
+/* eslint-disable */
+/* Adapted from nodemon's postinstall: https://github.com/remy/nodemon/blob/master/package.json */
+
+var msg = 'Take a look at https://opencollective.com/styled-components to help out styled-components’ maintainers';
```
Comment (mxstbr) [inline scripts/postinstall.js]: "Use styled-components at work? 💅 Consider supporting our development efforts at https://opencollective.com/styled-components"

Alternatively "Love styled-components?"

Comment (kitten) [reply scripts/postinstall.js]: I like first one :) that’s more specific I guess 👌

Comment (kitten) [reply scripts/postinstall.js]: updated the wording to the first option :) removed the emoji — as described in the PR message — I don't think it'd fair well with some

**Comment by dkfiresky** [comment]
@kitten thanks for shortening the post install message! ❤️
