### PR TITLE
Replace mixinDeep with a cycle-safe implementation

### LINKED ISSUE #3576: `mixinDeep` causes infinite recursion when `function.name-polyfill` is used.
## Reproduction
The [function.name-polyfill](https://www.npmjs.com/package/function.name-polyfill) polyfill causes infinite recursion in Styled components that use the `mixinDeep util`.

With this polyfill included, the [mixinDeep](https://github.com/styled-components/styled-components/blob/30dab74acedfd26d227eebccdcd18c92a1b3bd9b/packages/styled-components/src/utils/mixinDeep.ts) method ends up blowing the stack. 

This happens because the polyfill introduces a `Function.prototype._name` prototype method that itself has a `_name` property which is a function (and on and on it goes).

It feels like there are 2 potential issues in the `mixinDeep` implementation that cause this.  The main issue is that `for (const key in obj) {` is used for iteration without the `hasOwnProperty` check.  This doesn't feel right.  It feels like `for..of` should be used instead.  The second potential issue is that `isObject` returns `true` for functions.  Coupled together these 2 methods cause the infinite recursion.  

## Steps to reproduce
Include https://www.npmjs.com/package/function.name-polyfill in your code.  Trigger `mixinDeep` with an object that has a method defined.

## Expected Behavior
Code should work properly

## Actual Behavior
Application crashes due to stack overflow

### PR DESCRIPTION
**Pull request by 9still**
Fixes #3576

Since #2838, styled-components has been using a different (smaller) implementation of deep merge that doesn't play well with cyclical objects & particularly objects with cyclical prototypes.  In particular, this causes styled-components to blow the stack when used with some Function prototype extensions.

This PR replaces the mixinDeep implementation with a custom one that's closer to the [previously used library](https://github.com/mesqueeb/merge-anything) & is most similar in usage to [_.merge](https://lodash.com/docs/4.17.15#merge).  It keeps the tests unchanged, but adds a new one that explicitly ensures that cyclical objects don't blow the stack (try it with the old implementation if you want to see what happens in the current version).

See discussion in #3576 for further detail.

### CODE REVIEW

File: packages/styled-components/src/utils/mixinDeep.ts [hunk 1]
```diff
@@ -1,60 +1,33 @@
...
+function isRecursible(obj: any) {
+  return isPlainObject(obj) || Array.isArray(obj);
+}
 
-const isValidKey = (key: string) => {
-  return key !== '__proto__' && key !== 'constructor' && key !== 'prototype';
-};
+function mixinRecursively(target: any, source: any) {
+  const isRecursive = isRecursible(target);
+  for (const [key, sourceVal] of Object.entries(source)) {
```
Comment (kitten) [inline packages/styled-components/src/utils/mixinDeep.ts:10]: I'd love to avoid the use of `for-of` and `Object.entries` here. Simply because it's not a rather performant variant and it's imho a bit of unnecessary uses of two non-ES primitives. There's a simpler way here though 👀 

```js
function mixinRecursively(target: any, source: any) {
  if (Array.isArray(target)) {
    for (let key = 0; key < target.length; key++) {
      target[key] = mixinRecursively(target[key], source[key]);
    }
    return target
  } else if (isPlainObject(target)) {
    for (const key in source) {
      target[key] = mixinRecursively(target[key], source[key]);
    }
    return target
  } else if (source != null) {
    return source
  } else {
    return target
  }
}
```

_Note:_ We don't need a `hasOwnProperty` check here I realised, since it's a plain object.

I did notice that we're assigning and mutating here, but seems like we did that before, so 🤷 :+1:
Also, I may have forgotten a case, but simply pointing out here that we can avoid `for-of` and `Object.entries` here entirely without drawbacks :v:

Comment (9still) [reply packages/styled-components/src/utils/mixinDeep.ts]: Thanks for the suggestion @kitten! I refactored my original implementation to simplify & stop using `Object.entries` and `for..of` as you suggested.   Unfortunately couldn't use your implementation as is.  I added some tests in my latest commit that fail in your implementation (see below).    Also, while testing with your code I realized that `isPlainObject` was actually broken & was returning `true` for some objects with a custom prototype.  I updated the PR and took a stab at fixing that. 

Here is the test output with your implementation:

```
  ● should shallow merge properties if target is not a POJO or array

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `should shallow merge properties if target is not a POJO or array 1`

    - Snapshot  - 6
    + Received  + 0

      MyObj {
    -   "a": Object {
    -     "b": 2,
    -     "d": Object {
    -       "f": "f",
    -     },
    -   },
        "bar": 6,
        "foo": 5,
      }

      47 |   const obj2 = { a: { b: 2, d: { f: 'f' } } };
      48 |
    > 49 |   expect(mixinDeep(obj1, obj2)).toMatchInlineSnapshot(`
         |                                 ^
      50 | MyObj {
      51 |   "a": Object {
      52 |     "b": 2,

      at Object.<anonymous> (packages/styled-components/src/utils/test/mixinDeep.test.ts:49:33)

  ● should properly mixin arrays

    expect(received).toEqual(expected) // deep equality

    - Expected  - 5
    + Received  + 0

      Array [
        12,
    -   22,
    -   Object {
    -     "abc": 123,
    -   },
    -   true,
      ]

      158 |     60,
      159 |   ]);
    > 160 |   expect(mixinDeep([10], [11, 21, { abc: 123 }, true], [12, 22])).toEqual([
          |                                                                   ^
      161 |     12,
      162 |     22,
      163 |     { abc: 123 },

      at Object.<anonymous> (packages/styled-components/src/utils/test/mixinDeep.test.ts:160:67)
```

**Review by probablyup — APPROVED** [review]
Thank you!
