### PR TITLE
Reduce GC pressure by avoiding to create new object types

### LINKED ISSUE #2424: Flatten function performance issue v4
Having recently tried to upgrade our styled-components from v3 to v4 in a relatively large react app - we've ran into a strange performance issue that seems to be tied to the flatten function. When commenting out this part of flatten, the issue seems to resolve:

https://github.com/styled-components/styled-components/blob/9b81695d35074974c42b943a82456c9ae4b42500/packages/styled-components/src/utils/flatten.js#L59-L72

Here are screenshots of performance snapshots run with chrome dev tools when performing the same action in our app on v3 vs. v4:

**v3**
screen shot 2019-03-04 at 11 06 48 am

**v4**
screen shot 2019-03-04 at 10 59 45 am

Strangely, we have not been able to reproduce this in a clean slate react app.

## System:
 - OS: macOS High Sierra 10.13.6
 - CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
 - Memory: 2.29 GB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 8.14.0 - /usr/local/bin/node
 - Yarn: 1.13.0 - /usr/local/bin/yarn
 - npm: 6.5.0 - /usr/local/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.4.0 => 1.10.0
 - styled-components: ^4.1.3 => 4.1.3

## Reproduction

Unable to reproduce with a basic react app created via `create-react-app`. 

## Expected Behavior
Performance is as good if not better than v3.

## Actual Behavior
Performance is sluggish, significantly slower than v3.

### PR DESCRIPTION
**Pull request by alansouzati**
Closes #2424 

If you inspect the issue, you will see there is a major GC collector happening. `flatten` function is called a lot of times and every time we interpolate some style that code block is executed.

I'm avoiding to do `new chunk` and, instead, replaced with a new util called `isStatelessFunction`.

### CODE REVIEW

**Comment by probablyup** [comment]
@alansouzati can you add a changelog entry for this as well?

**Comment by probablyup** [comment]
Published under `styled-components@4.1.4-alpha.6` for testing

File: packages/styled-components/src/utils/flatten.js [hunk 1]
```diff
@@ -55,12 +56,13 @@ export default function flatten(chunk: any, executionContext: ?Object, styleShee
 
   /* Either execute or defer the function */
   if (isFunction(chunk)) {
-    if (executionContext) {
+    if (isStatelessFunction(chunk) && executionContext) {
```
Comment (tbranyen) [inline packages/styled-components/src/utils/flatten.js]: Since classes used to go into this code path and be checked if they are styled components or not, is this a breaking change?

**Comment by alansouzati** [comment]
@tbranyen pointed out that we may need to move the check for a full compatibility with the previous implementation. I'm taking a pass at that.

**Comment by alansouzati** [comment]
yeah we just validated it, it is not a breaking change. not further changes required it seems.

File: packages/styled-components/src/utils/flatten.js [hunk 2]
```diff
@@ -55,12 +56,13 @@ export default function flatten(chunk: any, executionContext: ?Object, styleShee
...
       let shouldThrow = false;
 
+      const result = chunk(executionContext);
+
       try {
```
Comment (alansouzati) [inline packages/styled-components/src/utils/flatten.js]: I think we can remove the try catch too!!

File: packages/styled-components/src/utils/flatten.js [hunk 3]
```diff
@@ -55,23 +56,14 @@ export default function flatten(chunk: any, executionContext: ?Object, styleShee
...
-        // eslint-disable-next-line new-cap
-        if (isElement(new chunk(executionContext))) {
-          shouldThrow = true;
-        }
-      } catch (e) {
-        /* */
-      }
-
-      if (shouldThrow) {
+      if (isElement(result)) {
```
Comment (kitten) [inline packages/styled-components/src/utils/flatten.js]: This doesn't quite seem safe. We're calling a function that might be a component and are doing so to throw a proper warning if it is;

I don't think I even agree with the previous error to be honest. A return value of a component might not always be an element, so this doesn't seem safe.

It's also unsafe to simply call this because components might contain hooks now, so we'd still need the try-catch: https://runkit.com/kitten/5c7f0daf31404d0011b3a130

@probablyup @mxstbr Are we sure we really need this error in production? Seems a little overzealous. Maybe an error in development or even just a `console.error` would do the trick?

@alansouzati btw, can you change the changelog entry to say it's reducing memory usage when running component selector styles? It seems a little extreme to call it a memory leak, since I don't think this is leaking, it simply seems to be allocating a lot of memory that the GC is slow to clean up 😅 Still bad, but I'd hate to confuse people tbh

Comment (alansouzati) [reply packages/styled-components/src/utils/flatten.js]: sure I can re-word the change log. I will wait to do that until you decide if you want the check or not. Then I will update the PR in one go.

Comment (alansouzati) [reply packages/styled-components/src/utils/flatten.js]: The goal of this PR was to maintain the same features while fixing an important issue that is affecting performance.

Comment (alansouzati) [reply packages/styled-components/src/utils/flatten.js]: Is there an easy way to tell if something is a styled component or not ? the check could be changed to validate that instead.

Comment (probablyup) [reply packages/styled-components/src/utils/flatten.js]: Yeah we have a util for it

Comment (alansouzati) [reply packages/styled-components/src/utils/flatten.js]: Cool does it make sense to use that instead? Unfortunately I don’t have a lot of the context for this.

**Comment by alansouzati** [comment]
any updates here? This is a rather pressing issue.

File: packages/styled-components/src/utils/flatten.js (hunk 3 above)
Comment (probablyup) [reply packages/styled-components/src/utils/flatten.js]: We check if it's a styled component at https://github.com/styled-components/styled-components/pull/2428/files#diff-ce0d3892db66efa4deef4063f44d3022R53 so not necessary

Comment (alansouzati) [reply packages/styled-components/src/utils/flatten.js]: I'm confused. can we remove the check or not?

Comment (probablyup) [reply packages/styled-components/src/utils/flatten.js]: I'm just responding to your earlier question, interpolated styled components are handled earlier in `flatten` so you don't have to worry about them in the try/catch

Comment (probablyup) [reply packages/styled-components/src/utils/flatten.js]: To @kitten's point, I think you're right and we can just do a dev-time warning & swallow the error in prod.

Comment (alansouzati) [reply packages/styled-components/src/utils/flatten.js]: is it ok to do that in a separate PR?

Comment (alansouzati) [reply packages/styled-components/src/utils/flatten.js]: I'm happy to do it in this PR if you can point me to a reference on how you are envision this.

File: CHANGELOG.md [hunk 4]
```diff
@@ -6,10 +6,13 @@ _The format is based on [Keep a Changelog](http://keepachangelog.com/) and this
 
 ## Unreleased
 
+- Fix memory leak issue when using component selector styles. (see [#2424](https://github.com/styled-components/styled-components/issues/2424)).
```
Comment (tbranyen) [inline CHANGELOG.md]: I noticed the comment saying to update this and I agree this isn't a leak, but helps prevent unnecessary GC cycles.

**Comment by mxstbr** [comment]
I agree with @kitten and @probablyup, two changes needed here:

- [ ] Move warning to be dev-only like our other warnings by checking `process.env.NODE_ENV`
- [ ] Rework changelog entry to say "reduce GC pressure" or something to that effect rather than memory leak

**Comment by alansouzati** [comment]
PR updated with the requested changes.

File: packages/styled-components/src/utils/flatten.js (hunk 1 above)
Comment (probablyup) [reply packages/styled-components/src/utils/flatten.js]: The `isStyledComponent` check happens higher in the function, so shouldn't be.

File: packages/styled-components/src/utils/flatten.js [hunk 5]
```diff
@@ -55,23 +55,19 @@ export default function flatten(chunk: any, executionContext: ?Object, styleShee
...
+        );
       }
 
-      if (shouldThrow) {
-        throw new StyledError(13, getComponentName(chunk));
-      }
-
-      return flatten(chunk(executionContext), executionContext, styleSheet);
+      return flatten(result, executionContext, styleSheet);
     } else return chunk;
```
Comment (probablyup) [inline packages/styled-components/src/utils/flatten.js]: The else branch here should also have the warning, no? If `isStatelessFunction(chunk)` returns false that implies a class, which is not a valid thing to interpolate.

Comment (probablyup) [reply packages/styled-components/src/utils/flatten.js]: ping @alansouzati

**Comment by probablyup** [comment]
I'd love to get the PR in this week and cut a minor release if you have time to address my last comment there!

File: packages/styled-components/src/utils/flatten.js (hunk 5 above)
Comment (alansouzati) [reply packages/styled-components/src/utils/flatten.js]: sorry I've missed this. I think the warning should be only in one place. probably by moving things around. let me take a careful pass at this.

Comment (alansouzati) [reply packages/styled-components/src/utils/flatten.js]: I don't think we should add a warning in the else.

`isStatelessFunction(chunk) && executionContext`

this is deferring the execution since `executionContext` is empty.

Comment (alansouzati) [reply packages/styled-components/src/utils/flatten.js]: @mxstbr please advise here. I don't have the full context of this flatten operation so I can definitely be missing something.

Comment (probablyup) [reply packages/styled-components/src/utils/flatten.js]: Ok I see! Yes this is perfect, thanks @alansouzati!
