### PR TITLE
Fix objects with functions - replace (objToCss) with (objToCssArray)

### LINKED ISSUE #2468: Functions inside of style objects, using multiple selectors
## Environment

`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard`
> ### System:
>  - OS: macOS High Sierra 10.13.6
>  - CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
>  - Memory: 86.22 MB / 16.00 GB
>  - Shell: 5.6 - /usr/local/bin/zsh
> ### Binaries:
>  - Node: 10.15.0 - /usr/local/bin/node
>  - Yarn: 1.5.1 - ~/.local/share/npm/bin/yarn
>  - npm: 6.8.0 - ~/.local/share/npm/bin/npm
>  - Watchman: 4.9.0 - /usr/local/bin/watchman

## Reproduction

See [CodeSandbox][repro]

[repro]: https://codesandbox.io/s/817wl8l08l

## Steps to reproduce

- Create an object style using comma-separated tags, and a property implemented as a function. See `BrokenStyle`, below:

```js
const WorkingStyle = createGlobalStyle`
  h1, h2, h3, h4, h5, h6 {
    font-family: ${({theme}) => theme.fonts.heading};
  }
`;

const BrokenStyle = createGlobalStyle({
  'h1, h2, h3, h4, h5, h6': {
    fontFamily: ({theme}) => theme.fonts.heading,
  },
});
```

## Expected Behavior

- The two implementations `WorkingStyle` and `BrokenStyle` are equivalent.

## Actual Behavior

- When using `BrokenStyle`, it seems as though `styled-components` stringifies my function and subsequently attempts to parse that as CSS. This new syntax is _amazing_, but not quite what I was expecting. Check out the output from the [above CodeSandbox][repro] (newlines added for clarity here):

```
h1 font-family:function fontFamily(_ref2),
h2 font-family:function fontFamily(_ref2),
h3 font-family:function fontFamily(_ref2),
h4 font-family:function fontFamily(_ref2),
h5 font-family:function fontFamily(_ref2),
h6 font-family:function fontFamily(_ref2){
  -webkit-var:theme = _ref2.theme;
  -moz-var:theme = _ref2.theme;
  -ms-var:theme = _ref2.theme;
  var:theme = _ref2.theme;
  return:theme.fonts.heading;
}
```

## Submitter note

If you'd like help with a fix, I'd love to tackle it; this is right up my alley. I'm not looking to enable my use case _per se_, I'd just like to prevent the next person from going through the same 20 minutes I did 😄 

I could see this being resolved in a few ways:

- Update `styled-components` so my sample works as I had expected
- Add a small note to the docs: "don't do this!" (Check out the implementation of `WorkaroundStyle` [in the CodeSandbox][repro]; technically this performs better, but there's no impact anyways since it usually runs once at page load time.)
- Implement a warning or safeguard to prevent this edge case (probably with an accompanying docs note)
- Something else?

### PR DESCRIPTION
**Pull request by d7my11**
Fixes: #2468 
Addresses: #2414
***

The issue was in `objToCss` method that didn't handle methods for objects.
- [x] Replace `objToCss` with `objToArray` which handles methods as well. 
- [x] Cover `createGlobalStyle` and `styled` with more test cases.

### CODE REVIEW

**Comment by mrmckeb** [comment]
Out of interest, are there any performance metrics around a) objects/functions over template literals, and b)  methods as properties?

**Comment by d7my11** [comment]
@mrmckeb I'm not 100% sure actually, but here is my understanding:
using template literal will be converted by babel to arrays if they have embedded expressions and get `.concat()`ed at the end.

Using objects gets converted by styled-components and it gets slower with nested objects because you have to go through every key for each object.

So, based on my assumptions, using template literal is faster specially if the object contains nested objects.

I would like to hear from somebody who is fully aware of the project to verify or correct me if i'm wrong.

**Comment by mrmckeb** [comment]
Good information, thanks @d7my11 - and great work.

**Comment by probablyup** [comment]
I'd also love if you could do this against `canary` instead or open a second PR for it.

**Comment by d7my11** [comment]
@probablyup is there any minor releases for bugs before merging `canary` into `master`? if so, will open a second PR for this. If not, will change the base branch.

**Comment by probablyup** [comment]
Yeah 4.x isn’t closed out yet

**Comment by d7my11** [comment]
Will open another PR then

**Comment by probablyup** [comment]
If you could build it on top of @kitten's latest PR that'd be great as I think he made some changes to code near what you're changing

**Comment by d7my11** [comment]
@probablyup opened another PR for `canary` #2542

**Comment by probablyup** [comment]
@d7my11 can you get this rebased against master? Looks like a test file just needs a little fix

**Comment by d7my11** [comment]
@probablyup done

File: packages/styled-components/src/utils/flatten.js [hunk 1]
```diff
@@ -14,19 +14,32 @@ import addUnitIfNeeded from './addUnitIfNeeded';
...
-    .filter(key => !isFalsish(obj[key]))
-    .map(key => {
-      if (isPlainObject(obj[key])) return objToCss(obj[key], key);
-      return `${hyphenate(key)}: ${addUnitIfNeeded(key, obj[key])};`;
+
+const objToCssArray = (obj: Object, prevKey?: string): Array<string | Function> => {
+  const rules = []
+  const keys = Object.keys(obj)
+
+  keys
```
Comment (probablyup) [inline packages/styled-components/src/utils/flatten.js]: this would be cleaner as a reduce I think

Comment (d7my11) [reply packages/styled-components/src/utils/flatten.js]: true, but usually it's slower than `.forEach` because the result has different type than the items. i did a quick benchmark for that [here](http://jsben.ch/A6Ad9)

Comment (probablyup) [reply packages/styled-components/src/utils/flatten.js]: Fair enough!

**Comment by probablyup** [comment]
Last thing, a changelog entry would be lovely

**Comment by d7my11** [comment]
@probablyup thanks for reviewing
