### PR TITLE
ssr backward-compat fix for ServerStyleSheet

### LINKED ISSUE #2637: v5 SSR Returning Empty Style Tags
## System:
 - OS: macOS High Sierra 10.13.4
 - CPU: (4) x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
 - Memory: 254.39 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
 - Yarn: 1.6.0 - /usr/local/bin/yarn
 - npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
 - Watchman: 4.7.0 - /usr/local/bin/watchman
## npmPackages:
 - babel-plugin-styled-components: ^1.10.1 => 1.10.1
 - styled-components: ^5.0.0-beta.3 => 5.0.0-beta.3

## Steps to reproduce
Within the context of an Express middleware:
```javascript
const sheet = new ServerStyleSheet()
const reactTree = (
  <StyleSheetManager sheet={sheet.instance}>
    <Router location={req.url} />
  </StyleSheetManager>
)

const html = ReactDOMServer.renderToString(reactTree)
const css = sheet.getStyleTags()
const { js } = flushChunks(clientStats, { chunkNames: flushChunkNames() })

res.status(200)
res.render('base', { html, css, js })
```

Base is just a Handlebars template, but it's not relevant. Can just print out contents of `css` here.

Within the context of my `.babelrc`:
```
"development": {
      "plugins": [
        "react-hot-loader/babel",
        [
          "styled-components",
          {
            "minify": false,
            "ssr": true,
            "displayName": true,
          }
        ]
      ]
    },
```

## Expected Behavior
Style tag (`css` above) in rendered HTML contains classes.

On server (and client hydration):
```javascript
<style data-styled data-styled-version="5.0.0-beta.3">
.kxoUDN{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-flex-direction:column-reverse;-ms-flex-direction:column-reverse;flex-direction:column-reverse;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-box-pack:end;-webkit-justify-content:flex-end;-ms-flex-pack:end;justify-content:flex-end;width:100vw;
</style>
```

## Actual Behavior
On Server:
```javascript
<style data-styled data-styled-version="5.0.0-beta.3"></style>
```

On Client Hydration:
```javascript
<style data-styled data-styled-version="5.0.0-beta.3">
.kxoUDN{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-flex-direction:column-reverse;-ms-flex-direction:column-reverse;flex-direction:column-reverse;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-box-pack:end;-webkit-justify-content:flex-end;-ms-flex-pack:end;justify-content:flex-end;width:100vw;
</style>
```

## Notes
`sheet.getStyleElement()` is the same result, a style tag that has `dangerouslySetInnerHTML: { _html: '' }`

### PR DESCRIPTION
**Pull request by probablyup**
add an alias "instance" to `ServerStyleSheet` so doing things the v4 way will continue to work

fixes #2637

### CODE REVIEW

File: packages/styled-components/src/models/ServerStyleSheet.js [hunk 1]
```diff
@@ -14,12 +14,18 @@ const CLOSING_TAG_R = /^\s*<\/[a-z]/i;
...
+
   sheet: StyleSheet;
 
   sealed: boolean;
 
   constructor() {
     this.sheet = new StyleSheet({ isServer: true });
+
+    // v4 backward compat
+    this.instance = this.sheet;
```
Comment (kitten) [inline packages/styled-components/src/models/ServerStyleSheet.js]: Lets remove this.sheet then and just rename it back 👍

**Comment by probablyup** [comment]
I originally did that but I do like the name sheet for internal use since
it’s more obvious
