### PR TITLE
fix createGlobalStyles + keyframes

### LINKED ISSUE #2027: Can't use keyframes in createGlobalStyle
Version: 4.0.0-beta.8

I ran into this problem when attempting to add an animation to a body background, so I created [this codesandbox reproduction](https://codesandbox.io/s/lzrxkq9kz).

Basically, when `keyframes` is used within a `createGlobalStyle` block, the value of the `animation` property is `[object Object]`

image

I searched around and couldn't find any mentions or reference to this issue, so I apologize if it's been brought up and you're aware of it.

### PR DESCRIPTION
**Pull request by probablyup**
~~I'm not sure if this is the right solution. Ideally we wouldn't run the `css` helper until render time but since we're hashing the completed rules I'm not sure if that can be changed.~~ It wasn't. But the PR has been updated to the correct solution.

Fixes #2027

### CODE REVIEW

File: src/utils/flatten.js [hunk 1]
```diff
@@ -28,7 +29,11 @@ export const objToCss = (obj: Object, prevKey?: string): string => {
  */
 const isFalsish = chunk => chunk === undefined || chunk === null || chunk === false || chunk === '';
 
-export default function flatten(chunk: any, executionContext: ?Object, styleSheet: ?Object): any {
+export default function flatten(
+  chunk: any,
+  executionContext: ?Object,
+  styleSheet: ?Object = StyleSheet.master
```
Comment (probablyup) [inline src/utils/flatten.js]: This is the primary change of the PR, assigning default back to `StyleSheet.master`

**Comment by probablyup** [comment]
I’m going to delete it. Drives me friggin crazy. Separate PR though

**Comment by imbhargav5** [comment]
Looks good to me. Perhaps we can add one test case where animation is added within interpolation just to be doubly sure? 
```
${props => props.animate ?  `animation: ${keyframeAnimation1} ease 1s` :  `` }
```

**Comment by Fer0x** [comment]
Offtopic: should we add some warning when someone tries to use keyframes within react-native?

**Comment by mxstbr** [comment]
@Fer0x yeah that seems smart! People have been confused about that. Wanna PR it?

**Comment by probablyup** [comment]
@imbhargav5 that example actually wouldn't work because of the lack of `css` helper haha.

**Comment by imbhargav5** [comment]
Alright then, I think we can merge this if all is good?
