### PR TITLE
Fix defaultProps/props theme theming

### LINKED ISSUE #247: Dynamicly update theme on react-storybook with knob
## Version
1.0.5

## Reproduction
https://github.com/clempat/styled-component-theming

## Steps to reproduce
- See the repo above
- See the result there: http://piano-tuner-larry-61732.netlify.com/

## Expected Behavior
- When updating the color on react-storybook-knob. it should update the button color

## Actual Behavior
- It get out of sync and display the color previously selected

I am not sure it is a problem with styled-components but if I take a look into the react dev tool I see the theme there correctly updated.

### LINKED ISSUE #252: Bugs in handling theme from defaultProps / props
## Version
1.1.1

## Reproduction
Couldn't install styled-components on webpackbin

## Steps to reproduce

```js
import { mount as render } from 'enzyme';
import jsdom from 'mocha-jsdom';

describe('theming', () => {
  jsdom();

  beforeEach(() => {
    styled = resetStyled()
  })

  it('should properly render with the same theme from default props on re-render', () => {
    const Comp1 = styled.div`
      color: ${props => props.theme.color};
    `

    Comp1.defaultProps = {
      theme: {
        color: "purple"
      }
    }
    const wrapper = render(
      <Comp1 />
    )
    expectCSSMatches(`.a { color: purple; }`)

    wrapper.update();
    expectCSSMatches(`.a { color: purple; }`)
  })

  it('should properly update style if theme is changed', () => {
    const Comp1 = styled.div`
      color: ${props => props.theme.color};
    `

    Comp1.defaultProps = {
      theme: {
        color: "purple"
      }
    }
    const wrapper = render(
      <Comp1 />
    )
    expectCSSMatches(`.a { color: purple; }`)

    wrapper.setProps({ theme: { color: 'pink' } })
    expectCSSMatches(`.a { color: purple; }.b { color: pink; }`)
  })

});

```

## Expected Behavior

Should pass tests.

## Actual Behavior

Fails in both cases.

First case fails because it will render with `.a { color: ; }` in second render.

Second case fails because it will not react to new `theme` so it won't render `.b { color: pink; }`.

### PR DESCRIPTION
**Pull request by michalkvasnicak**
Fixes #252 
Fixes #247

### CODE REVIEW

File: src/models/StyledComponent.js [hunk 1]
```diff
@@ -50,20 +50,32 @@ export default (ComponentStyle: Function) => {
...
         }
       }
 
       componentWillReceiveProps(nextProps: any) {
+        if (!nextProps.theme) {
+          return
+        }
+
+        // compare if there is any change
+        if (JSON.stringify(nextProps.theme) === JSON.stringify(this.state.theme)) {
```
Comment (mxstbr) [inline src/models/StyledComponent.js]: Should this be a deep equality check instead of `JSON.stringify`? What's the difference?

File: src/models/StyledComponent.js [hunk 2]
```diff
@@ -50,20 +50,32 @@ export default (ComponentStyle: Function) => {
...
+          return
+        }
+
+        const { theme } = nextProps
```
Comment (mxstbr) [inline src/models/StyledComponent.js]: Let's move this destructure to the function argument and use the `theme` variable throughout `componentWillReceiveProps({ theme })`.

File: src/test/theme.test.js [hunk 3]
```diff
@@ -1,13 +1,15 @@
 // @flow
+import jsdom from 'mocha-jsdom';
 import React from 'react'
-import { render } from 'enzyme'
+import { mount as render } from 'enzyme'
```
Comment (mxstbr) [inline src/test/theme.test.js]: Why do we rename this to `render`? That's a separate mode, let's rename all instances of `render` to `mount` instead, otherwise this could be confusing.

File: src/models/StyledComponent.js (hunk 1 above)
Comment (mxstbr) [inline src/models/StyledComponent.js]: Since the main difference between a deep equality check and the `JSON.stringify` method (which I find very smart btw, have never heard of that before) is that the deep equality check doesn't care about the ordering of the elements. ([see here for more info](http://www.mattzeunert.com/2016/01/28/javascript-deep-equal.html))

How big is the a dependency that can do deep equality?

Comment (michalkvasnicak) [inline src/models/StyledComponent.js]: @mxstbr I don't know if there is need to do other equality check than `===`. Because if we pass the same theme to `generateAndInjectStyles()` we should get the same result right?

I am looking on this https://github.com/substack/node-deep-equal.

File: src/test/theme.test.js (hunk 3 above)
Comment (michalkvasnicak) [inline src/test/theme.test.js]: Yeah I forgot to refactor this :)

File: src/models/StyledComponent.js (hunk 2 above)
Comment (michalkvasnicak) [inline src/models/StyledComponent.js]: Done. I hope flowtype is correct.

File: src/models/StyledComponent.js [hunk 4]
```diff
@@ -50,20 +50,27 @@ export default (ComponentStyle: Function) => {
...
         }
       }
 
-      componentWillReceiveProps(nextProps: any) {
-        const generatedClassName = this.generateAndInjectStyles(
-          this.state.theme || this.props.theme,
-          nextProps
-        )
-        this.setState({ generatedClassName })
+      componentWillReceiveProps({ theme }: { theme: ?{ [key: string]: mixed } }) {
```
Comment (michalkvasnicak) [inline src/models/StyledComponent.js]: @mxstbr This annotation is the same as `Theme` in `ThemeProvider`. I can export `Theme` type from `ThemeProvider` component and use it here. Then it would be `{ theme: ?Theme }`.

File: src/models/StyledComponent.js (hunk 1 above)
Comment (michalkvasnicak) [inline src/models/StyledComponent.js]: Yeah this solution is better than introducing new dependency :)

**Comment by mxstbr** [comment]
Oh sorry, I just realized that this will probably increase our rendering time since we're now doing a full `jsdom` render for every test. Do you mind adding a `describe('jsdom', () => { jsdom() })` section in which we can put all the tests that require a full DOM render (i.e. `mount`), but use enyzmes `render` for all the original ones? That should speed it up quite a bit I think.

Sorry for the troubles, thanks!

**Comment by michalkvasnicak** [comment]
@mxstbr done 😉

**Comment by michalkvasnicak** [comment]
@mxstbr Do not merge this yet, there is buf in `componentWillReceiveProps`. We can't bail out at all because it will not react to props change so for example. If you have a style that is using props to calculate something, then it won't propagate changes at all.

**Comment by michalkvasnicak** [comment]
@mxstbr ok fixed

**Comment by mxstbr** [comment]
Amazing work, thanks so much! Shipping a new version with these changes very soon!
