### PR TITLE
Prevent ServerStyleSheet from emitting empty tags 

### LINKED ISSUE #3291: Empty style tags in streaming SSR output | Breaks in IE11
_**Context**_: Universal React application with styled-components running on Hapi server, streaming SSR enabled.

**_Problem_**: `"Unable to get property 'split' of undefined or null reference"` at `style.innerHTML.split('/!sc/\n')` in `rehydrateSheetFromTag()`

**_RCA_**: Looks like some of the style tags that are generated on server in streaming output are empty and they end up inside a SVG element (I think that's because they are always placed at top a chunk?). Now the problem is IE11 returns `undefined` for innerHTML of a style tag which is inside SVG and that throws an exception at `style.innerHTML.split('/!sc/\n')` in rehydrateSheetFromTag(). There are other empty styles tags who's parent node is not SVG and IE11 would just return innerHTML as `""`, and in turn `innerHTML.split('/!sc/\n')` would just return empty array, so no problem there. 

Screen Shot 2020-09-26 at 11 36 38 PM

**_Questions_**: 

1. So I am trying to figure out why would there be an empty style tag generated on server? anyone here with internal of knowledge of styled-components know in what circumstances that can happen? Does that it indicate much larger issue underneath from application standpoint?
2. If those empty style tags are expected in some scenario, can we add a null check for innerHTML before we try to split it? I can send a PR up for this.
3. Is my understanding correct about why a style tag would end up inside a SVG? I can confirm this doesn't happen for all pages, only for certain pages with varying amount of data.

### System:
 - OS: macOS 10.15.3
 - CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
 - Memory: 73.68 MB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh
### Binaries:
 - Node: 12.17.0 - ~/.nvm/versions/node/v12.17.0/bin/node
 - Yarn: 1.22.4 - ~/.yarn/bin/yarn
 - npm: 6.14.4 - ~/.nvm/versions/node/v12.17.0/bin/npm
### npmPackages:
 - babel-plugin-styled-components: ^1.10.7 => 1.10.7
 - styled-components: ^5.0.1 => 5.1.1

### PR DESCRIPTION
**Pull request by kitten**
Resolve #3291

_Note:_ There's no need to port this to `main` i.e. v6, as we won't be supporting IE11 for it as discussed a while ago
(For anyone following along, check #3333)

### CODE REVIEW

File: packages/styled-components/src/sheet/Rehydration.js [hunk 1]
```diff
@@ -52,7 +52,7 @@ const rehydrateNamesFromContent = (sheet: Sheet, id: string, content: string) =>
 };
 
 const rehydrateSheetFromTag = (sheet: Sheet, style: HTMLStyleElement) => {
-  const parts = style.innerHTML.split(SPLITTER);
+  const parts = (style.innerHTML || '').split(SPLITTER);
```
Comment (probablyup) [inline packages/styled-components/src/sheet/Rehydration.js:55]: This change seems unrelated?

**Review by probablyup — APPROVED** [review]

File: packages/styled-components/src/sheet/Rehydration.js (hunk 1 above)
Comment (kitten) [reply packages/styled-components/src/sheet/Rehydration.js:55]: it isn't really super unrelated. The original issue said that the main problem is that this returns undefined for empty elements in IE11. Basically, I'm just afraid that IE11 users could still experience the bug itself when some HTML snippet is generated using an old version of the library. Basically, just wanted to cover this on both ends

Comment (probablyup) [reply packages/styled-components/src/sheet/Rehydration.js:55]: I think `.innerHTML` will always return an empty string though
